# Generated by Django 4.2.24 on 2025-09-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='items_views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
